FROM golang:1.15 AS builder
WORKDIR /srv
COPY . .
ARG GOARCH=
ARG CGO_ENABLED=0
RUN go build github.com/snsinfu/reconf
RUN go build -o rtun-server ./server/cmd

FROM scratch
COPY --from=builder /srv/reconf /srv/rtun-server /
COPY --from=builder /srv/docker/rtun-server.yml.template /config/
ENV RTUN_AGENT=
ENTRYPOINT ["/reconf", "-w", "/config/rtun-server.yml", "/rtun-server"]
CMD ["-f", "/config/rtun-server.yml"]
