name: test

on: push

jobs:

  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.20"

      - run: go vet ./...
      - run: go test ./...
      - run: tests/run

  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.agent

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.server
